export enum Subtitle {
    UpcomingConcerts = "Upcoming Concerts",
    GlobalMap = "Our Global Concert Map",
    HearOurSound = "Hear Our Sound",
    ArchiveConcerts = "Concert Archive",
    TrioMembers = "Khachaturian Trio Members"
}


export enum ButtonText {
    ViewAll = "View all concerts",
    Details = "Details",
    ViewMore = "View more",
    ViewMorePhotos = "View more photos",
    ArchiveConcerts = "Concert archive",
    UpcomingConcerts = "Upcoming concerts",
    YoutubeLinkFirstText = "Watch more videos on our",
    YoutubeLinkSecondText = "YouTube channel",
}

export enum FooterContent {
    WebsiteBy = "Website designed and developed by",
    SkillsUp = "SkillsUp Technologies",
    Copyright = "© 2024 Khachaturian Trio"
} 

export enum UpcomingConcerts {
    NoData1 = "We have just wrapped up a wonderful tour! While we are taking a short break, we are already busy planning our next performances.",
    NoData2 = "Stay tuned – exciting new concerts will be announced soon!",
    NoData3 = "Let’s imagine here’s an extra text, I think now it looks not so bad... We have just wrapped up a wonderful tour! While we are taking a short break, we are already busy planning our next performances.",
} 

export enum BiographyText {
    TrioPart1 = "Khachaturian Trio was founded as trio “Arsika” in 1999. The ensemble had tours in over 100 cities in 40 countries of the world /Armenia, Russia, Kazakhstan, Georgia, Moldova, the Baltic countries, Germany, Italy, Spain, Belgium, Malta, Poland, Czech Republic, Austria, the USA, Canada, Australia, Lebanon, Costa Rica, Mexico, Uruguay, Argentina, China, Japan, etc./, and gives for about 70 concerts in a season. The Trio has performed in most famous concert halls, such as Musikverein, Wien, Laeiszhalle, Hamburg, Gewandhaus, Leipzig, Gasteig-Philharmonie, Munich, Purcell Room, London, Suntory Hall, Tokyo, Koerner Hall, Toronto. Participated in a number of prestigious festivals - the Festival de las Artes (Costa Rica), Festival International Cervantino (Mexico), 'Russiche Kammermusikfest' in Hamburg, Malta International Music Festival to name a few. ",
    TrioPart2 = "The Trio’s performances have been frequently broadcasted by TV and Radio. Nine CDs, dedicated to Armenian and Russian music, were recorded by musicians, including CD, released by Sony, double CD, dedicated to chamber music of Aram Khachaturian and many others. The musical critics highly praise Khachaturian Trio’s virtuous performances, subtle sense of style, warmest sound, brilliant and deep musicality. Since 2006 the Trio has included the following members: Armine Grigoryan /piano/, Karen Shahgaldyan /violin/, Karen Kocharyan /cello/. In 2008 the ensemble was renamed after the outstanding Armenian composer Aram Khachaturian. ",
    TrioPart3 = "Several years ago, the ensemble presented a colossal project, dedicated to Aram Khachaturian, which then lasted worldwide: the musicians performed three concertos during a night by Khachaturian - for piano, for violin and Concerto-Rhapsody for cello. The Trio has performed all Khachaturian’s solo sonatas - for piano, for violin, for cello and for viola, (violist - Maxim Novikov) many times in different cities and concert halls. Very important part of the Trio's repertoire is Triple Concerto by Beethoven. The Trio works in tight collaboration with contemporary composers. It has premiered a number of new works, which were commissioned by them. Khahcaturian Trio’s repertoire covers a wide range of music styles. In 2010 the musicians together with Aram Khachaturian’s close friend, benefactor Assadour Guzelian, established Classical Music Development Foundation. Members of the Trio are involved in pedagogic activity giving master classes in music schools of various regions of Armenia. Khachaturian Trio has good connections with Aram Khachaturian Museum in Yerevan, which is possible to call a 'laboratory' for musicians of the Trio. The Trio members have recorded CDs, their concerts often take place in the Museum Concert Hall, as well as several educational projects, which were inspired by musicians of the Trio were held in Maestro’s house.",
    ArmineGrigoryan = "Armine Grigoryan",
    ArmineGrigoryanBiography1 = " is one of the brightest representatives of Armenian contemporary pianists. The famous Armenian composer Eduard Mirzoyan expressed his admiration with these words: “…I can’t keep admiring Armine’s play and I am constantly eager to listen”.  She received her entire musical education first in Yerevan Tchaikovsky school of music, then in Yerevan Komitas Conservatoire and postgraduate studies under the supervision of professors Georgy and Sergey Saradjians, obtaining excellent professional qualities. This is evident in her appearances as a soloist and collaborative pianist.Armine Grigoryan as soloist and chamber musician has toured CIS, Italy, Germany, United Kingdom, Austria, Check Republic, Spain, Belgium, Bulgaria, UAE, Kazakhstan, Lebanon, Baltics, China, Japan, Australia, USA, Canada, Mexico and others.Armine Grigoryan became a Double Laureate of “Roma 2003” International Pianists Competition, where she also was awarded a special prize and medal of the Chamber of Deputies of Rome. In the same year Armine Grigoryan with Sona Barseghyan (piano duo “Sonet”) won prize of International Competition, organized by “Frederic Chopin” Association in Rome, and took also Special prize for the Best Performance of pieces by Sergio Calligaris.She is the recipient of special awards as a piano collaborative pianist in several International competitions.Armine Grigoryan has released several CDs (“Unknown Khachaturian” among them). ",
    ArmineGrigoryanBiography2 = "Since 2005 Armine’s artistic originality also shines in her concert programs as a pianist of the Aram Khachaturian Trio along with the talented musicians – violinist Karen Shahgaldyan and cellist Karen Kocharyan. Outside of Armenia the concerts of Trio were held in many countries of the world: in such Prestigious concert halls as “Musicverein” in Vienna, “Laiezhalle” in Hamburg, “Gewandhaus” in Leipzig, “Gasteig philharmonic” in Munich, “Queen Elizabeth Hall” in London, “Suntory Hall” in Tokio, “Koerner Hall” in Toronto.  Together with the other members of the Trio and with the support of London resident benefactor Assadour Guzelian, Armine Grigoryan established the Classical Music Development Foundation, with the aim to propagandize the Armenian composers’ works and to support young gifted musicians. She was awarded the Medals of the Ministry of Culture of Poland and Armenia.Armine Grigoryan is a Professor of the Yerevan State Conservatory.Since 2004 as the director of the Aram Khachaturian Museum she widely popularizes Khachaturian’s music and name both in the homeland and abroad, establishes new links with other museums of the world.",
    KarenShahgaldyan = "Karen Shahgaldyan",
    KarenShahgaldyanBiography = " is one of the most brilliant musicians of modern Russia. Laureate of Pablo Sarasate International Competition. He finished the Moscow State Conservatory at the class of Professor Victor Tretiakov and the Graduate School of the Moscow State Conservatory into the class of Professor M. Glezarova. Karen attended master-classes of Yehudi Menuhin, Vladimir Spivakov, Grigorii Zhislin, Evgeniia Chugaeva. Several years Karen performed in the orchestra 'Virtuosos of Moscow' under the direction of Vladimir Spivakov. He performed at such halls as Carnegie Hall, New York, Bolshoy Hall, Moscow, Royal Festival Hall, London, Musikverein, Wien, Laeizhalle, Hamburg, Purcell Room, London, Suntory Hall, Tokyo, Opera City Hall, Tokyo and others. He visited with concerts more than 200 cities in such countries, as USA, China, South Korea, Germany, Great Britain, Japan, Austria, Australia, Sweden, Spain, Italy, Latvia, Lietuva, Czech Republic, Georgia, Moldova, Russia and Armenia. From 2006 violinist of Khachaturian trio.",
    KarenQocharyan = "Karen Kocharyan",
    KarenQocharyanBiography = " graduated from Yerevan Tchaykovsky School of Music (Class of Prof. Alexander Chaushyan) and Yerevan State Conservatory (class of Prof. Geronty Talalyan). Karen Kocharyan is one of the founding members of the Khachatyryan trio, he was first solo cellist of the Armenian Chamber Players (ACP), Associate concertmaster of the Armenian Philharmonic Orchestra. He has toured with the Armenian Chamber Players and Armenian Philharmonic Orchestra throughout Europe, featuring as soloist as well. In 2005 Karen Kocharyan, under conductor Alexander Ivashkin (UK), appeared as soloist with Armenian Philharmonic Orchestra and in 2006 with Eduard Topchjan and Pasadena LAC Symphony Orchestra took part in Beethoven’s Triple Concerto appearance. From 2017 concertmaster of Shenzhen Symphony Orchestra, China. Karen Kocharyan is an active chamber musician. As a chamber player Karen Kocharyan collaborate with such renowned musicians as Yuri Zhislin, Boris Andrianov, Alexander Ghindin, Tamaki Kawakubo, Wolfgang Meyer, Zandra McMaster, Alessio Bax, Anton Sorokow, Diemut Poppen, Daishin Kashimoto."
}